name: flutter_mvvm
description: fmvvm is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 0.1.0
homepage: https://github.com/Mahdibenamor/Fmvvm

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  get_it: ">=7.2.0 <8.0.0"
  provider: ^6.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.1
