name: example
description: A simple command-line application.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it:  ">=7.0.0 <8.0.0"
  injectable_mvvm: ^0.1.0



dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.4.0
  effective_dart: ^1.3.2
  lints: ^2.1.0
  injectable_mvvm_generator:
    path: ../../injectable_mvvm_generator
